# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "email": "osbourne@oscorp.com",
   "password": "ihatepeter"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "osbourne@oscorp.com",
   "password": "ihatepeter"
}

###
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMzcxMDksImV4cCI6MTY2NzMzNzE2OX0.rTN-1JH4zCiaiJOP-u6UZ9rJBCllAQWYdhdxW0E9KDc
Content-Type: application/json
